### ISSUE TITLE
How to add Multiple script(.js) file from local folder in src in config.js file

### ISSUE THREAD

**Issue by KamranMaqbool** [abumalick/gatsby-plugin-load-script#75]

**Comment by abumalick** [comment]
Oh this is a good question, this plugin is not loading script files via webpack.

What do you think about placing these files in static folder instead? It would not be compiled by webpack but it should work.

**Comment by abumalick** [comment]
I just added some documentation for using a js file from the static folder: https://github.com/abumalick/gatsby-plugin-load-script#local-script-from-static-folder

You can see how it is implemented on the demo here:
https://github.com/abumalick/gatsby-plugin-load-script/commit/cf64371a039cbd58f12006d3507b682ae5a41ff7

Sorry for the late reply, I didn't see the notification
